# Generated by Django 6.0.5 on 2026-06-02 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schoolactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('crop_type', models.CharField(max_length=100)),
                ('soil_ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('moisture_level', models.CharField(blank=True, max_length=50)),
                ('observations', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_logs', to='core.studentprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
