# Generated by Django 6.0.5 on 2026-06-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studentprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='day_of_week',
            field=models.CharField(default='Monday', max_length=15),
        ),
        migrations.AddField(
            model_name='course',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
