# Generated by Django 6.0.5 on 2026-06-03 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_day_of_week_course_end_time_course_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=45000.0, max_digits=8)),
                ('library_dues', models.DecimalField(decimal_places=2, default=1500.0, max_digits=6)),
                ('lab_dues', models.DecimalField(decimal_places=2, default=3500.0, max_digits=6)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_record', to='core.studentprofile')),
            ],
        ),
    ]
